"""Central registry for notification-capable app events.

Future Cursor edits should add notification-capable actions here first. The
app syncs these definitions into NotificationRule rows without overwriting
admin-edited rule content.
"""

from __future__ import annotations

from copy import deepcopy


RECIPIENT_PRESETS: dict[str, dict] = {
    "project_team": {
        "all_project_members": True,
    },
    "production_team": {
        "post_scopes": ["needs_production_team"],
        "project_roles": ["producer", "post_producer"],
    },
    "color_team": {
        "post_scopes": ["needs_color_grading"],
        "job_titles": ["Colorist", "Color Supervisor"],
    },
    "vfx_team": {
        "post_scopes": ["needs_vfx"],
        "job_titles": ["VFX Supervisor", "VFX Artist", "Compositor"],
    },
    "dit_online_conform": {
        "job_titles": ["DIT", "Online Conform", "Conform Artist", "Data Wrangler", "Machine Room"],
    },
    "edit_team": {
        "post_scopes": ["needs_offline_editing", "needs_online_editing"],
        "job_titles": ["Editor", "Assistant Editor", "Online Editor"],
    },
    "assigned_user": {"dynamic": ["assigned_user"]},
    "requested_by": {"dynamic": ["requested_by"]},
    "admins": {
        "access_roles": ["admin"],
        "job_titles": ["Security / Access Control Admin"],
    },
}


COMMON_VARIABLES = [
    "project_id",
    "project_name",
    "actor_id",
    "actor_name",
    "user_name",
    "current_date",
    "current_time",
    "notification_title",
    "notification_body",
]

TASK_VARIABLES = ["task_id", "task_title", "task_status", "task_priority", "assigned_user_name", "requested_by_name"]
WORK_REQUEST_VARIABLES = [
    "request_id",
    "request_title",
    "request_status",
    "request_priority",
    "previous_status",
    "comment",
    "assigned_user_name",
    "requested_by_name",
]
EDITING_ITEM_VARIABLES = ["editing_item_id", "editing_item_code", "editing_item_title", "editing_item_type", "editing_item_status"]
CONFORM_VARIABLES = [
    "handoff_file_type",
    "handoff_file_name",
    "handoff_file_label",
    "guide_video_name",
    "guide_video_label",
    "failure_reason",
    "failure_types",
    "previous_status",
    "previous_status_label",
    "new_status",
    "new_status_label",
]
COLOR_VARIABLES = ["color_status", "color_route_status", "color_handling", "colorist_name", "color_version_label"]
VFX_VARIABLES = ["shot_id", "shot_code", "shot_status", "vfx_artist_name"]
PRODUCTION_VARIABLES = ["episode_number", "episode_title", "scene_number", "scene_title", "shooting_day_name"]
DELIVERY_VARIABLES = ["delivery_type", "delivery_status", "delivery_file_name"]
WORKFLOW_VARIABLES = [
    "approval_request_id",
    "request_type",
    "request_type_label",
    "request_title",
    "request_status",
    "target_user_name",
    "target_project_name",
    "workflow_payload_summary",
    "reason",
]


def _vars(*groups: list[str]) -> list[str]:
    out: list[str] = []
    for group in (COMMON_VARIABLES, *groups):
        for key in group:
            if key not in out:
                out.append(key)
    return out


NOTIFICATION_EVENTS: dict[str, dict] = {
    "conform_requested": {
        "label": "Conform Requested",
        "category": "conform",
        "description": "Sent when a conform task is requested for an editing item.",
        "source": "Color / Conform",
        "source_file": "conform_routes.py",
        "source_function": "_notify_conform_requested",
        "source_feature": "Color Conform",
        "default_title": "Conform requested: {{ editing_item_code }}",
        "default_body": "{{ actor_name }} requested conform for {{ editing_item_code }} · {{ editing_item_title }} in {{ project_name }}.\n\nHandoff file: {{ handoff_file_label }}\nGuide video: {{ guide_video_label }}\n\nAssigned to: {{ assigned_user_name }}",
        "default_cta_label": "Open Color Item",
        "default_cta_url": "/projects/{{ project_id }}/color/items/{{ editing_item_id }}",
        "default_recipients": {"preset": "dit_online_conform", "project_roles": ["post_producer"]},
        "variables": _vars(TASK_VARIABLES, EDITING_ITEM_VARIABLES, CONFORM_VARIABLES),
        "is_active": True,
    },
    "conform_started": {
        "label": "Conform Started",
        "category": "conform",
        "description": "Sent when conform work starts.",
        "source": "Color / Conform",
        "source_file": "conform_routes.py",
        "source_function": "_notify_status_change",
        "source_feature": "Color Conform",
        "default_title": "Conform started: {{ editing_item_code }}",
        "default_body": "{{ actor_name }} started conforming {{ editing_item_code }} · {{ editing_item_title }} in {{ project_name }}.",
        "default_cta_label": "Open Color Item",
        "default_cta_url": "/projects/{{ project_id }}/color",
        "default_recipients": {"preset": "color_team", "project_roles": ["producer", "post_producer"]},
        "variables": _vars(TASK_VARIABLES, EDITING_ITEM_VARIABLES, CONFORM_VARIABLES),
        "is_active": True,
    },
    "conform_status_changed": {
        "label": "Conform Status Changed",
        "category": "conform",
        "description": "Sent when a conform task status is updated from the tasks list.",
        "source": "Color / Conform",
        "source_file": "conform_routes.py",
        "source_function": "apply_conform_status",
        "source_feature": "Color Conform",
        "default_title": "Conform status updated: {{ editing_item_code }}",
        "default_body": "{{ actor_name }} changed conform status for {{ editing_item_code }} · {{ editing_item_title }} in {{ project_name }} from {{ previous_status_label }} to {{ new_status_label }}.\n\nHandoff file: {{ handoff_file_label }}\nGuide video: {{ guide_video_label }}\n\nAssigned to: {{ assigned_user_name }}",
        "default_cta_label": "Open Color Item",
        "default_cta_url": "/projects/{{ project_id }}/color/items/{{ editing_item_id }}",
        "default_recipients": {
            "post_scopes": ["needs_color_grading", "needs_production_team"],
        },
        "variables": _vars(TASK_VARIABLES, EDITING_ITEM_VARIABLES, CONFORM_VARIABLES),
        "dedupe_enabled": False,
        "is_active": True,
    },
    "conform_done": {
        "label": "Conform Done",
        "category": "conform",
        "description": "Sent when conform is completed.",
        "source": "Color / Conform",
        "source_file": "conform_routes.py",
        "source_function": "_notify_status_change",
        "source_feature": "Color Conform",
        "default_title": "Conform done: {{ editing_item_code }}",
        "default_body": "{{ actor_name }} finished conforming {{ editing_item_code }} · {{ editing_item_title }} in {{ project_name }}.\n\nThe item is ready for color grading.",
        "default_cta_label": "Open Color Item",
        "default_cta_url": "/projects/{{ project_id }}/color",
        "default_recipients": {"preset": "color_team", "project_roles": ["producer", "post_producer"]},
        "variables": _vars(TASK_VARIABLES, EDITING_ITEM_VARIABLES, CONFORM_VARIABLES),
        "is_active": True,
    },
    "conform_failed": {
        "label": "Conform Failed",
        "category": "conform",
        "description": "Sent when conform fails.",
        "source": "Color / Conform",
        "source_file": "conform_routes.py",
        "source_function": "apply_conform_failure",
        "source_feature": "Color Conform",
        "default_title": "Conform failed: {{ editing_item_code }}",
        "default_body": "{{ actor_name }} marked conform as failed for {{ editing_item_code }} · {{ editing_item_title }} in {{ project_name }}.\n\nReason:\n{{ failure_reason }}\n\nFailure types:\n{{ failure_types }}",
        "default_cta_label": "Open Failure Note",
        "default_cta_url": "/tasks#task-{{ task_id }}",
        "default_recipients": {"preset": "color_team", "post_scopes": ["needs_offline_editing", "needs_online_editing"], "project_roles": ["producer", "post_producer"]},
        "variables": _vars(TASK_VARIABLES, EDITING_ITEM_VARIABLES, CONFORM_VARIABLES),
        "priority": "urgent",
        "is_active": True,
    },
    "conform_done_with_issues": {
        "label": "Conform Done With Issues",
        "category": "conform",
        "description": "Sent when conform completes with tracked issues.",
        "source": "Color / Conform",
        "source_file": "conform_routes.py",
        "source_function": "apply_conform_done_with_issues",
        "source_feature": "Color Conform",
        "default_title": "Conform done with issues: {{ editing_item_code }}",
        "default_body": "{{ actor_name }} marked conform done with issues for {{ editing_item_code }} · {{ editing_item_title }} in {{ project_name }}.\n\nReason:\n{{ issue_reason }}\n\nIssue types:\n{{ failure_types }}\n\nColor can start: {{ color_can_start }}",
        "default_cta_label": "Open Color Item",
        "default_cta_url": "/projects/{{ project_id }}/color/items/{{ editing_item_id }}",
        "default_recipients": {"preset": "color_team", "post_scopes": ["needs_offline_editing", "needs_online_editing"], "project_roles": ["producer", "post_producer"]},
        "variables": _vars(TASK_VARIABLES, EDITING_ITEM_VARIABLES, CONFORM_VARIABLES),
        "priority": "high",
        "is_active": True,
    },
    "handoff_file_uploaded": {
        "label": "Handoff File Uploaded",
        "category": "conform",
        "description": "Sent when a color/conform handoff file is uploaded.",
        "source": "Color / Conform",
        "source_file": "conform_routes.py",
        "source_function": "emit_upload_notifications",
        "source_feature": "Color Handoff",
        "default_title": "Color handoff uploaded",
        "default_body": "{{ actor_name }} uploaded for {{ project_name }} · {{ editing_item_title }}.\n\nHandoff file: {{ handoff_file_name }}\nGuide video: {{ guide_video_label }}",
        "default_cta_label": "Request Conform",
        "default_cta_url": "/editing-items/{{ editing_item_id }}/color/request-conform",
        "default_recipients": {"preset": "dit_online_conform", "post_scopes": ["needs_color_grading", "needs_online_editing"], "job_titles": ["Colorist"]},
        "variables": _vars(EDITING_ITEM_VARIABLES, CONFORM_VARIABLES),
        "is_active": True,
    },
    "handoff_file_deleted": {
        "label": "Handoff File Deleted",
        "category": "conform",
        "description": "Sent when an edit/color handoff file is deleted.",
        "source": "Color / Conform",
        "source_file": "color_grading_routes.py",
        "source_function": "_notify_edit_version_delete_departments",
        "source_feature": "Color Handoff",
        "default_title": "{{ notification_title }}",
        "default_body": "{{ notification_body }}",
        "default_cta_label": "Open Color",
        "default_cta_url": "/projects/{{ project_id }}/color",
        "default_recipients": {"preset": "color_team"},
        "variables": _vars(EDITING_ITEM_VARIABLES, CONFORM_VARIABLES),
        "is_active": True,
    },
    "task_assigned": {
        "label": "Task Assigned",
        "category": "tasks",
        "description": "Sent when a task is assigned.",
        "source": "Tasks",
        "source_file": "app.py",
        "source_function": "tasks_create",
        "source_feature": "Tasks",
        "default_title": "New task assigned: {{ task_title }}",
        "default_body": "{{ actor_name }} assigned you a task in {{ project_name }}.\n\nTask: {{ task_title }}\nPriority: {{ task_priority }}",
        "default_cta_label": "Open Task",
        "default_cta_url": "/tasks#task-{{ task_id }}",
        "default_recipients": {"preset": "assigned_user"},
        "variables": _vars(TASK_VARIABLES),
        "is_active": True,
    },
    "task_done": {
        "label": "Task Done",
        "category": "tasks",
        "description": "Sent when a task is marked done.",
        "source": "Tasks",
        "source_file": "app.py",
        "source_function": "tasks_set_status",
        "source_feature": "Tasks",
        "default_title": "Task done: {{ task_title }}",
        "default_body": "{{ actor_name }} marked {{ task_title }} as done in {{ project_name }}.",
        "default_cta_label": "Open Task",
        "default_cta_url": "/tasks#task-{{ task_id }}",
        "default_recipients": {"preset": "requested_by", "project_roles": ["post_producer"]},
        "variables": _vars(TASK_VARIABLES),
        "is_active": True,
    },
    "work_request_assigned": {
        "label": "Request Assigned",
        "category": "requests",
        "description": "Sent when a work request is assigned.",
        "source": "Requests",
        "source_file": "work_request_routes.py",
        "source_function": "requests_create",
        "source_feature": "Requests",
        "default_title": "A new request was assigned to you: {{ request_title }}",
        "default_body": "A new request was assigned to you: {{ request_title }}.\n\nPriority: {{ request_priority }}\nProject: {{ project_name }}",
        "default_cta_label": "Open Request",
        "default_cta_url": "/requests/{{ request_id }}",
        "default_recipients": {"preset": "assigned_user"},
        "variables": _vars(WORK_REQUEST_VARIABLES),
        "is_active": True,
    },
    "work_request_started": {
        "label": "Request Started",
        "category": "requests",
        "description": "Sent when a work request is started.",
        "source": "Requests",
        "source_file": "work_request_routes.py",
        "source_function": "requests_start",
        "source_feature": "Requests",
        "default_title": "{{ actor_name }} started request: {{ request_title }}",
        "default_body": "{{ actor_name }} started request: {{ request_title }}.\nPrevious status: {{ previous_status }}\nNew status: {{ request_status }}\nProject: {{ project_name }}",
        "default_cta_label": "Open Request",
        "default_cta_url": "/requests/{{ request_id }}",
        "default_recipients": {"dynamic": ["assigned_user", "requested_by"]},
        "variables": _vars(WORK_REQUEST_VARIABLES),
        "is_active": True,
    },
    "work_request_finished": {
        "label": "Request Finished",
        "category": "requests",
        "description": "Sent when a work request is finished.",
        "source": "Requests",
        "source_file": "work_request_routes.py",
        "source_function": "requests_finish",
        "source_feature": "Requests",
        "default_title": "{{ actor_name }} finished request: {{ request_title }}",
        "default_body": "{{ actor_name }} finished request: {{ request_title }}.\nPrevious status: {{ previous_status }}\n{% if comment %}Comment: {{ comment }}{% endif %}",
        "default_cta_label": "Open Request",
        "default_cta_url": "/requests/{{ request_id }}",
        "default_recipients": {"dynamic": ["assigned_user", "requested_by"]},
        "variables": _vars(WORK_REQUEST_VARIABLES),
        "is_active": True,
    },
    "work_request_failed": {
        "label": "Request Failed",
        "category": "requests",
        "description": "Sent when a work request is marked failed.",
        "source": "Requests",
        "source_file": "work_request_routes.py",
        "source_function": "requests_fail",
        "source_feature": "Requests",
        "default_title": "{{ actor_name }} marked request as failed: {{ request_title }}",
        "default_body": "{{ actor_name }} marked request as failed: {{ request_title }}.\nReason: {{ comment }}",
        "default_cta_label": "Open Request",
        "default_cta_url": "/requests/{{ request_id }}",
        "default_recipients": {"dynamic": ["assigned_user", "requested_by"]},
        "variables": _vars(WORK_REQUEST_VARIABLES),
        "is_active": True,
    },
    "work_request_reopened": {
        "label": "Request Reopened",
        "category": "requests",
        "description": "Sent when a finished or failed work request is reopened.",
        "source": "Requests",
        "source_file": "work_request_routes.py",
        "source_function": "requests_reopen",
        "source_feature": "Requests",
        "default_title": "{{ actor_name }} reopened request: {{ request_title }}",
        "default_body": "{{ actor_name }} reopened request: {{ request_title }}.\nPrevious status: {{ previous_status }}",
        "default_cta_label": "Open Request",
        "default_cta_url": "/requests/{{ request_id }}",
        "default_recipients": {"dynamic": ["assigned_user", "requested_by"]},
        "variables": _vars(WORK_REQUEST_VARIABLES),
        "is_active": True,
    },
    "conference_invite": {
        "label": "Conference Invite",
        "category": "chat",
        "description": "Sent when a user is invited to a chat conference.",
        "source": "Chat",
        "source_file": "app.py",
        "source_function": "notify_conference_invite",
        "source_feature": "Chat",
        "default_title": "{{ notification_title }}",
        "default_body": "{{ notification_body }}",
        "default_cta_label": "Open Chat",
        "default_cta_url": "/chat",
        "default_recipients": {"preset": "assigned_user"},
        "variables": _vars(["thread_id", "conference_id"]),
        "is_active": True,
    },
    "editing_item_sent_to_color": {
        "label": "Editing Item Sent To Color",
        "category": "color",
        "description": "Sent when an episode/editing item is sent to Color.",
        "source": "Color",
        "source_file": "color_grading_routes.py",
        "source_function": "_notify_send_to_color_department",
        "source_feature": "Color",
        "default_title": "{{ project_name }} · Editing item sent to Color: {{ editing_item_code }}",
        "default_body": "{{ actor_name }} sent {{ editing_item_code }} ({{ editing_item_title }}) to Color Department in {{ project_name }}.\n\nHandling: {{ color_handling }}\nStatus: {{ color_status }}",
        "default_cta_label": "Open Color Item",
        "default_cta_url": "/projects/{{ project_id }}/color/items/{{ editing_item_id }}",
        "default_recipients": {"preset": "color_team", "project_roles": ["post_producer"]},
        "variables": _vars(EDITING_ITEM_VARIABLES, COLOR_VARIABLES, PRODUCTION_VARIABLES),
        "is_active": True,
    },
    "color_version_uploaded": {
        "label": "Color Version Uploaded",
        "category": "color",
        "description": "Sent when a color version is uploaded.",
        "source": "Color",
        "source_file": "color_grading_routes.py",
        "source_function": "_notify_edit_version_upload_departments",
        "source_feature": "Color",
        "default_title": "Color version uploaded: {{ editing_item_code }}",
        "default_body": "{{ actor_name }} uploaded a color version for {{ editing_item_code }} · {{ editing_item_title }}.",
        "default_cta_label": "Open Color Item",
        "default_cta_url": "/projects/{{ project_id }}/color",
        "default_recipients": {"preset": "color_team", "project_roles": ["post_producer"]},
        "variables": _vars(EDITING_ITEM_VARIABLES, COLOR_VARIABLES),
        "is_active": True,
    },
    "color_status_changed": {
        "label": "Color Status Changed",
        "category": "color",
        "description": "Sent for color supervisor status warnings.",
        "source": "Color",
        "source_file": "color_grading_routes.py",
        "source_function": "_notify_color_supervisors",
        "source_feature": "Color",
        "default_title": "{{ notification_title }}",
        "default_body": "{{ notification_body }}",
        "default_cta_label": "Open Color",
        "default_cta_url": "/projects/{{ project_id }}/color",
        "default_recipients": {"job_titles": ["Color Supervisor", "Head of Color"]},
        "variables": _vars(COLOR_VARIABLES),
        "is_active": True,
    },
    "color_item_assigned": {
        "label": "Color Item Assigned",
        "category": "color",
        "description": "Sent when a color item is assigned to a colorist.",
        "source": "Color",
        "source_file": "color_item_routes.py",
        "source_function": "_notify_colorist_assigned",
        "source_feature": "Color",
        "default_title": "{{ notification_title }}",
        "default_body": "{{ notification_body }}",
        "default_cta_label": "Open Color",
        "default_cta_url": "/projects/{{ project_id }}/color",
        "default_recipients": {"dynamic": ["color_assigned_user"]},
        "variables": _vars(EDITING_ITEM_VARIABLES, COLOR_VARIABLES),
        "is_active": True,
    },
    "color_conform_requested": {
        "label": "Color Conform Requested",
        "category": "color",
        "description": "Sent when Color Conform tasks are requested.",
        "source": "Color",
        "source_file": "color_grading_routes.py",
        "source_function": "_notify_color_conform_assignees",
        "source_feature": "Color Conform",
        "default_title": "{{ notification_title }}",
        "default_body": "{{ notification_body }}",
        "default_cta_label": "Open Task",
        "default_cta_url": "/tasks#task-{{ task_id }}",
        "default_recipients": {"preset": "assigned_user"},
        "variables": _vars(TASK_VARIABLES),
        "is_active": True,
    },
    "vfx_shot_assigned": {
        "label": "VFX Shot Assigned",
        "category": "vfx",
        "description": "Sent when a VFX shot is assigned.",
        "source": "VFX",
        "source_file": "app.py",
        "source_function": "_notify_vfx_dept_shot_assigned",
        "source_feature": "VFX Department",
        "default_title": "Shot assigned: {{ shot_code }}",
        "default_body": "{{ notification_body }}",
        "default_cta_label": "Open VFX",
        "default_cta_url": "/projects/{{ project_id }}/vfx",
        "default_recipients": {"dynamic": ["vfx_assigned_user"]},
        "variables": _vars(VFX_VARIABLES),
        "is_active": True,
    },
    "vfx_shot_status_changed": {
        "label": "VFX Shot Status Changed",
        "category": "vfx",
        "description": "Sent when a VFX shot status changes.",
        "source": "VFX",
        "source_file": "app.py",
        "source_function": "_notify_vfx_dept_shot_status_change",
        "source_feature": "VFX Department",
        "default_title": "{{ notification_title }}",
        "default_body": "{{ notification_body }}",
        "default_cta_label": "Open VFX",
        "default_cta_url": "/projects/{{ project_id }}/vfx",
        "default_recipients": {"dynamic": ["vfx_assigned_user", "department_assigned_user"]},
        "variables": _vars(VFX_VARIABLES),
        "is_active": True,
    },
    "vfx_shot_approved": {
        "label": "VFX Shot Approved",
        "category": "vfx",
        "description": "Sent when a VFX shot is approved.",
        "source": "VFX",
        "source_file": "app.py",
        "source_function": "_notify_vfx_dept_shot_status_change",
        "source_feature": "VFX Department",
        "default_title": "VFX shot approved: {{ shot_code }}",
        "default_body": "{{ actor_name }} approved {{ shot_code }} in {{ project_name }}.",
        "default_cta_label": "Open VFX",
        "default_cta_url": "/projects/{{ project_id }}/vfx",
        "default_recipients": {"preset": "vfx_team", "post_scopes": ["needs_online_editing", "needs_color_grading"], "project_roles": ["post_producer"]},
        "variables": _vars(VFX_VARIABLES),
        "is_active": True,
    },
    "vfx_shot_delivered": {
        "label": "VFX Shot Delivered",
        "category": "vfx",
        "description": "Sent when a VFX shot is delivered.",
        "source": "VFX",
        "source_file": "app.py",
        "source_function": "_notify_vfx_dept_shot_status_change",
        "source_feature": "VFX Department",
        "default_title": "{{ notification_title }}",
        "default_body": "{{ notification_body }}",
        "default_cta_label": "Open VFX",
        "default_cta_url": "/projects/{{ project_id }}/vfx",
        "default_recipients": {"dynamic": ["vfx_assigned_user", "department_assigned_user"]},
        "variables": _vars(VFX_VARIABLES),
        "is_active": True,
    },
    "vfx_shot_sent_to_department": {
        "label": "VFX Shot Sent To Department",
        "category": "vfx",
        "description": "Sent when a shot enters the in-house VFX department.",
        "source": "VFX",
        "source_file": "app.py",
        "source_function": "_notify_vfx_supervisors_shot_sent_to_department",
        "source_feature": "VFX Department",
        "default_title": "{{ notification_title }}",
        "default_body": "{{ notification_body }}",
        "default_cta_label": "Open VFX",
        "default_cta_url": "/projects/{{ project_id }}/vfx",
        "default_recipients": {"job_titles": ["VFX Supervisor"]},
        "variables": _vars(VFX_VARIABLES),
        "is_active": True,
    },
    "vfx_shot_unassigned": {
        "label": "VFX Shot Unassigned",
        "category": "vfx",
        "description": "Sent when a user is unassigned from a VFX shot.",
        "source": "VFX",
        "source_file": "app.py",
        "source_function": "_vfx_clear_shot_department_overrides",
        "source_feature": "VFX Department",
        "default_title": "{{ notification_title }}",
        "default_body": "{{ notification_body }}",
        "default_cta_label": "Open VFX",
        "default_cta_url": "/projects/{{ project_id }}/vfx",
        "default_recipients": {"dynamic": ["vfx_assigned_user"]},
        "variables": _vars(VFX_VARIABLES),
        "priority": "high",
        "is_active": True,
    },
    "vfx_client_review_action": {
        "label": "VFX Client Review Action",
        "category": "vfx",
        "description": "Sent for VFX client review actions.",
        "source": "VFX",
        "source_file": "app.py",
        "source_function": "_vfx_notify_client_review_action",
        "source_feature": "Client Review",
        "default_title": "{{ notification_title }}",
        "default_body": "{{ notification_body }}",
        "default_cta_label": "Open VFX",
        "default_cta_url": "/projects/{{ project_id }}/vfx",
        "default_recipients": {"project_roles": ["producer", "post_producer"], "preset": "vfx_team"},
        "variables": _vars(VFX_VARIABLES),
        "is_active": True,
    },
    "hdd_over_capacity": {
        "label": "HDD Over Capacity",
        "category": "system",
        "description": "Sent when a hard disk goes over capacity.",
        "source": "Machine Room",
        "source_file": "app.py",
        "source_function": "evaluate_hdd_notifications",
        "source_feature": "Machine Room",
        "default_title": "{{ notification_title }}",
        "default_body": "{{ notification_body }}",
        "default_cta_label": "",
        "default_cta_url": "",
        "default_recipients": {"preset": "production_team"},
        "variables": _vars(),
        "priority": "urgent",
        "is_active": True,
    },
    "hdd_low_free": {
        "label": "HDD Low Free Space",
        "category": "system",
        "description": "Sent when a hard disk has low free space.",
        "source": "Machine Room",
        "source_file": "app.py",
        "source_function": "evaluate_hdd_notifications",
        "source_feature": "Machine Room",
        "default_title": "{{ notification_title }}",
        "default_body": "{{ notification_body }}",
        "default_cta_label": "",
        "default_cta_url": "",
        "default_recipients": {"preset": "production_team"},
        "variables": _vars(),
        "priority": "high",
        "is_active": True,
    },
    "booking_overlap": {
        "label": "Booking Overlap",
        "category": "booking",
        "description": "Sent when a booking overlap is detected.",
        "source": "Booking",
        "source_file": "app.py",
        "source_function": "emit_booking_overlap_alert",
        "source_feature": "Booking",
        "default_title": "{{ notification_title }}",
        "default_body": "{{ notification_body }}",
        "default_cta_label": "",
        "default_cta_url": "",
        "default_recipients": {"preset": "production_team"},
        "variables": _vars(["booking_id"]),
        "priority": "high",
        "is_active": True,
    },
    "shooting_day_created": {
        "label": "Shooting Day Created",
        "category": "production",
        "description": "Sent when a shooting day is created.",
        "source": "Production",
        "source_file": "app.py",
        "source_function": "emit_shooting_day_created_activity",
        "source_feature": "Production",
        "default_title": "{{ notification_title }}",
        "default_body": "{{ notification_body }}",
        "default_cta_label": "",
        "default_cta_url": "",
        "default_recipients": {"preset": "production_team"},
        "variables": _vars(PRODUCTION_VARIABLES),
        "is_active": True,
    },
    "critical_note_added": {
        "label": "Critical Note Added",
        "category": "production",
        "description": "Sent when a production critical note is added.",
        "source": "Production",
        "source_file": "app.py",
        "source_function": "emit_shooting_day_critical_created",
        "source_feature": "Production",
        "default_title": "{{ notification_title }}",
        "default_body": "{{ notification_body }}",
        "default_cta_label": "",
        "default_cta_url": "",
        "default_recipients": {"preset": "project_team"},
        "variables": _vars(PRODUCTION_VARIABLES),
        "priority": "urgent",
        "is_active": True,
    },
    "critical_note_solved": {
        "label": "Critical Note Solved",
        "category": "production",
        "description": "Sent when a production critical note is solved.",
        "source": "Production",
        "source_file": "app.py",
        "source_function": "emit_shooting_day_critical_solved",
        "source_feature": "Production",
        "default_title": "{{ notification_title }}",
        "default_body": "{{ notification_body }}",
        "default_cta_label": "",
        "default_cta_url": "",
        "default_recipients": {"preset": "production_team"},
        "variables": _vars(PRODUCTION_VARIABLES),
        "is_active": True,
    },
    "machine_room_copy_finished": {
        "label": "Machine Room Copy Finished",
        "category": "system",
        "description": "Sent when Machine Room finishes a copy task.",
        "source": "Machine Room",
        "source_file": "app.py",
        "source_function": "tasks_machine_room_stream_finish",
        "source_feature": "Machine Room",
        "default_title": "{{ notification_title }}",
        "default_body": "{{ notification_body }}",
        "default_cta_label": "",
        "default_cta_url": "",
        "default_recipients": {"preset": "project_team"},
        "variables": _vars(TASK_VARIABLES),
        "is_active": True,
    },
    "ingest_batch_created": {
        "label": "Ingest Batch Created",
        "category": "system",
        "description": "Sent when a new media ingest batch is created from Machine Room.",
        "source": "Machine Room",
        "source_file": "machine_room_dashboard_routes.py",
        "source_function": "machine_room_ingest_create",
        "source_feature": "Machine Room Ingest",
        "default_title": "New ingest batch: {{ batch_name }}",
        "default_body": "{{ actor_name }} created ingest batch “{{ batch_name }}” for {{ project_name }}.\n\nShooting day: {{ shooting_day_label }}\nCopy status: {{ copy_status }}\nMedia sources: {{ source_count }}\nDestination: {{ destination_path }}",
        "default_cta_label": "Open Ingest",
        "default_cta_url": "/projects/{{ project_id }}/machine-room/ingest",
        "default_recipients": {
            "post_scopes": ["needs_production_team", "needs_offline_editing"],
        },
        "variables": _vars(PRODUCTION_VARIABLES, ["batch_id", "batch_name", "shooting_day_label", "source_count", "destination_path", "copy_status"]),
        "is_active": True,
    },
    "machine_room_convert_started": {
        "label": "Machine Room Convert Started",
        "category": "system",
        "description": "Sent when Machine Room starts a convert task.",
        "source": "Machine Room",
        "source_file": "app.py",
        "source_function": "tasks_machine_room_stream_finish",
        "source_feature": "Machine Room",
        "default_title": "{{ notification_title }}",
        "default_body": "{{ notification_body }}",
        "default_cta_label": "",
        "default_cta_url": "",
        "default_recipients": {"preset": "project_team"},
        "variables": _vars(TASK_VARIABLES),
        "is_active": True,
    },
    "machine_room_convert_declined": {
        "label": "Machine Room Convert Declined",
        "category": "system",
        "description": "Sent when Machine Room declines convert after copy.",
        "source": "Machine Room",
        "source_file": "app.py",
        "source_function": "tasks_machine_room_stream_finish",
        "source_feature": "Machine Room",
        "default_title": "{{ notification_title }}",
        "default_body": "{{ notification_body }}",
        "default_cta_label": "",
        "default_cta_url": "",
        "default_recipients": {"preset": "project_team"},
        "variables": _vars(TASK_VARIABLES),
        "is_active": True,
    },
    "machine_room_convert_finished": {
        "label": "Machine Room Convert Finished",
        "category": "system",
        "description": "Sent when Machine Room finishes a convert task.",
        "source": "Machine Room",
        "source_file": "app.py",
        "source_function": "tasks_machine_room_stream_finish",
        "source_feature": "Machine Room",
        "default_title": "{{ notification_title }}",
        "default_body": "{{ notification_body }}",
        "default_cta_label": "",
        "default_cta_url": "",
        "default_recipients": {"preset": "project_team"},
        "variables": _vars(TASK_VARIABLES),
        "is_active": True,
    },
    "machine_room_copy_cancelled": {
        "label": "Machine Room Copy Cancelled",
        "category": "system",
        "description": "Sent when a Machine Room copy task is cancelled.",
        "source": "Machine Room",
        "source_file": "app.py",
        "source_function": "tasks_machine_room_stream_cancel_delete",
        "source_feature": "Machine Room",
        "default_title": "{{ notification_title }}",
        "default_body": "{{ notification_body }}",
        "default_cta_label": "",
        "default_cta_url": "",
        "default_recipients": {"preset": "project_team"},
        "variables": _vars(TASK_VARIABLES),
        "priority": "high",
        "is_active": True,
    },
    "machine_room_convert_cancelled": {
        "label": "Machine Room Convert Cancelled",
        "category": "system",
        "description": "Sent when a Machine Room convert task is cancelled.",
        "source": "Machine Room",
        "source_file": "app.py",
        "source_function": "tasks_machine_room_stream_cancel_delete",
        "source_feature": "Machine Room",
        "default_title": "{{ notification_title }}",
        "default_body": "{{ notification_body }}",
        "default_cta_label": "",
        "default_cta_url": "",
        "default_recipients": {"preset": "project_team"},
        "variables": _vars(TASK_VARIABLES),
        "priority": "high",
        "is_active": True,
    },
    "chat_mention": {
        "label": "Chat Mention",
        "category": "chat",
        "description": "Realtime mention event. It is listed for visibility but remains system-only.",
        "source": "Chat",
        "source_file": "app.py",
        "source_function": "chat message/task mention emits",
        "source_feature": "Chat",
        "default_title": "{{ notification_title }}",
        "default_body": "{{ notification_body }}",
        "default_cta_label": "Open Chat",
        "default_cta_url": "/chat",
        "default_recipients": {"dynamic": ["assigned_user"]},
        "variables": _vars(["message_id", "thread_id"]),
        "is_active": False,
        "status": "not connected",
    },
    "notifications_changed": {
        "label": "Notifications Changed",
        "category": "system",
        "description": "System-critical realtime panel refresh. Not configurable as a rule.",
        "source": "System",
        "source_file": "app.py",
        "source_function": "_notification_push_realtime_for_project",
        "source_feature": "Notification Bell",
        "default_title": "",
        "default_body": "",
        "default_cta_label": "",
        "default_cta_url": "",
        "default_recipients": {},
        "variables": _vars(),
        "is_active": False,
        "status": "not connected",
    },
    "workflow_request_created": {
        "label": "Workflow Request Created",
        "category": "workflow",
        "description": "Generic admin notification when a workflow request is created.",
        "source": "Workflow Engine",
        "source_file": "workflow_engine.py",
        "source_function": "WorkflowEngine.create_request",
        "default_title": "{{ request_title|default('Workflow request created') }}",
        "default_body": "A new {{ request_type_label|default('workflow') }} request was created.\n\nStatus: {{ request_status|default('pending') }}\nSummary: {{ workflow_payload_summary|default('') }}",
        "default_cta_label": "Open",
        "default_cta_url": "/admin/approvals{% if approval_request_id %}/{{ approval_request_id }}{% endif %}",
        "default_recipients": {"preset": "admins"},
        "variables": _vars(WORKFLOW_VARIABLES),
        "is_active": True,
    },
    "workflow_request_approved": {
        "label": "Workflow Request Approved",
        "category": "workflow",
        "description": "Generic user/admin notification when a workflow request is approved.",
        "source": "Workflow Engine",
        "source_file": "workflow_engine.py",
        "source_function": "WorkflowEngine.approve_request",
        "default_title": "{{ request_title|default('Workflow request approved') }}",
        "default_body": "Your {{ request_type_label|default('workflow') }} request was approved.\n\nSummary: {{ workflow_payload_summary|default('') }}",
        "default_recipients": {"dynamic": ["requested_by"]},
        "variables": _vars(WORKFLOW_VARIABLES),
        "is_active": True,
    },
    "workflow_request_rejected": {
        "label": "Workflow Request Rejected",
        "category": "workflow",
        "description": "Generic user notification when a workflow request is rejected.",
        "source": "Workflow Engine",
        "source_file": "workflow_engine.py",
        "source_function": "WorkflowEngine.reject_request",
        "default_title": "{{ request_title|default('Workflow request rejected') }}",
        "default_body": "Your {{ request_type_label|default('workflow') }} request was rejected.\n\nReason: {{ reason|default('') }}",
        "default_recipients": {"dynamic": ["requested_by"]},
        "variables": _vars(WORKFLOW_VARIABLES),
        "is_active": True,
    },
    "workflow_request_completed": {
        "label": "Workflow Request Completed",
        "category": "workflow",
        "description": "Generic admin notification when a workflow request finishes execution.",
        "source": "Workflow Engine",
        "source_file": "workflow_engine.py",
        "source_function": "WorkflowEngine.approve_request",
        "default_title": "{{ request_title|default('Workflow request completed') }}",
        "default_body": "A {{ request_type_label|default('workflow') }} request completed.\n\nSummary: {{ workflow_payload_summary|default('') }}",
        "default_recipients": {"preset": "admins"},
        "variables": _vars(WORKFLOW_VARIABLES),
        "is_active": True,
    },
    # --- Enterprise user lifecycle events (approval + auditing) ---
    "user_registered": {
        "label": "New User Registration",
        "category": "security",
        "description": "Sent to admins when a user registers and awaits approval.",
        "source": "Enterprise Approvals",
        "source_file": "account_approval_routes.py",
        "source_function": "account_approval",
        "default_title": "New user registration (awaiting approval)",
        "default_body": "{{ actor_name }} submitted a new registration. Review and approve or reject in the Approvals queue.",
        "default_cta_label": "Open",
        "default_cta_url": "/admin/approvals",
        "default_recipients": {"preset": "admins"},
        "variables": _vars(),
        "is_active": True,
    },
    "user_approved": {
        "label": "Account Approved",
        "category": "security",
        "description": "Sent to the user after administrator approval.",
        "source": "Enterprise Approvals",
        "source_file": "account_approval_routes.py",
        "source_function": "account_approval",
        "default_title": "Account approved",
        "default_body": "Your account has been approved.\n\nAssigned job title: {{ assigned_job_title }}\nAssigned access role: {{ assigned_access_role }}\nDepartment: {{ department }}",
        "default_recipients": {"dynamic": ["requested_by"]},
        "variables": _vars(),
        "is_active": True,
    },
    "user_rejected": {
        "label": "Account Rejected",
        "category": "security",
        "description": "Sent to the user after administrator rejection.",
        "source": "Enterprise Approvals",
        "source_file": "account_approval_routes.py",
        "source_function": "account_approval",
        "default_title": "Account rejected",
        "default_body": "Your registration request was not approved.\n\nReason: {{ reason }}",
        "default_recipients": {"dynamic": ["requested_by"]},
        "variables": _vars(),
        "is_active": True,
    },
    "account_suspended": {
        "label": "Account Suspended",
        "category": "security",
        "description": "Sent to the user when an administrator suspends an account.",
        "source": "Enterprise Approvals",
        "source_file": "account_approval_routes.py",
        "source_function": "account_approval",
        "default_title": "Account suspended",
        "default_body": "Your account has been suspended.\n\nReason: {{ reason }}\nSuspension end: {{ end_date }}",
        "default_recipients": {"dynamic": ["requested_by"]},
        "variables": _vars(),
        "is_active": True,
    },
    "account_disabled": {
        "label": "Account Disabled",
        "category": "security",
        "description": "Sent to the user when an administrator disables an account.",
        "source": "Enterprise Approvals",
        "source_file": "account_approval_routes.py",
        "source_function": "account_approval",
        "default_title": "Account disabled",
        "default_body": "Your account has been disabled.\n\nReason: {{ reason }}",
        "default_recipients": {"dynamic": ["requested_by"]},
        "variables": _vars(),
        "is_active": True,
    },
    "account_reactivation_request": {
        "label": "Account Reactivation Request",
        "category": "security",
        "description": "Sent to admins when a suspended/disabled user requests reactivation.",
        "source": "Enterprise Approvals",
        "source_file": "account_approval_routes.py",
        "source_function": "account_approval",
        "default_title": "Reactivation request submitted",
        "default_body": "A suspended/disabled user submitted a reactivation request. Review it in the Reactivation Requests tab.\n\nReason: {{ reason }}",
        "default_cta_label": "Open",
        "default_cta_url": "/admin/approvals",
        "default_recipients": {"preset": "admins"},
        "variables": _vars(),
        "is_active": True,
    },
    "account_reactivated": {
        "label": "Account Reactivated",
        "category": "security",
        "description": "Sent to the user after reactivation approval.",
        "source": "Enterprise Approvals",
        "source_file": "account_approval_routes.py",
        "source_function": "account_approval",
        "default_title": "Account reactivated",
        "default_body": "Your account has been reactivated. You may now use the application.",
        "default_recipients": {"dynamic": ["requested_by"]},
        "variables": _vars(),
        "is_active": True,
    },
    "account_reactivation_rejected": {
        "label": "Reactivation Rejected",
        "category": "security",
        "description": "Sent to the user when their reactivation request is rejected.",
        "source": "Enterprise Approvals",
        "source_file": "account_approval_routes.py",
        "source_function": "account_approval",
        "default_title": "Reactivation rejected",
        "default_body": "Your reactivation request was not approved.\nReason: {{ reason }}",
        "default_recipients": {"dynamic": ["requested_by"]},
        "variables": _vars(),
        "is_active": True,
    },
    "role_change_request": {
        "label": "Role Change Request",
        "category": "security",
        "description": "Sent to admins when a user requests sensitive profile changes.",
        "source": "Enterprise Approvals",
        "source_file": "account_approval_routes.py",
        "source_function": "account_approval",
        "default_title": "Role change request submitted",
        "default_body": "A user submitted role/profile changes requiring approval. Review and decide in the Role Change Requests tab.",
        "default_cta_label": "Open",
        "default_cta_url": "/admin/approvals",
        "default_recipients": {"preset": "admins"},
        "variables": _vars(),
        "is_active": True,
    },
    "role_change_approved": {
        "label": "Role Change Approved",
        "category": "security",
        "description": "Sent to the user after approval of sensitive profile changes.",
        "source": "Enterprise Approvals",
        "source_file": "account_approval_routes.py",
        "source_function": "account_approval",
        "default_title": "Profile changes approved",
        "default_body": "Your profile changes were approved.\n\nAssigned job title: {{ assigned_job_title }}\nAssigned access role: {{ assigned_access_role }}\nDepartment: {{ department }}",
        "default_recipients": {"dynamic": ["requested_by"]},
        "variables": _vars(),
        "is_active": True,
    },
    "role_change_rejected": {
        "label": "Role Change Rejected",
        "category": "security",
        "description": "Sent to the user after rejection of sensitive profile changes.",
        "source": "Enterprise Approvals",
        "source_file": "account_approval_routes.py",
        "source_function": "account_approval",
        "default_title": "Profile changes rejected",
        "default_body": "Your requested profile changes were not approved.\nReason: {{ reason }}",
        "default_recipients": {"dynamic": ["requested_by"]},
        "variables": _vars(),
        "is_active": True,
    },
    "permission_change_request": {
        "label": "Permission Change Request",
        "category": "security",
        "description": "Sent to admins when permission changes require approval.",
        "source": "Enterprise Approvals",
        "source_file": "account_approval_routes.py",
        "source_function": "account_approval",
        "default_title": "Permission change request submitted",
        "default_body": "A permission change request was submitted and requires administrator review.",
        "default_cta_label": "Open",
        "default_cta_url": "/admin/approvals",
        "default_recipients": {"preset": "admins"},
        "variables": _vars(),
        "is_active": True,
    },
    "permission_change_approved": {
        "label": "Permission Change Approved",
        "category": "security",
        "description": "Sent to the user after permission approval.",
        "source": "Enterprise Approvals",
        "source_file": "account_approval_routes.py",
        "source_function": "account_approval",
        "default_title": "Permissions approved",
        "default_body": "Your permission changes were approved.",
        "default_recipients": {"dynamic": ["requested_by"]},
        "variables": _vars(),
        "is_active": True,
    },
    "permission_change_rejected": {
        "label": "Permission Change Rejected",
        "category": "security",
        "description": "Sent to the user after permission rejection.",
        "source": "Enterprise Approvals",
        "source_file": "account_approval_routes.py",
        "source_function": "account_approval",
        "default_title": "Permissions rejected",
        "default_body": "Your permission changes were not approved.\nReason: {{ reason }}",
        "default_recipients": {"dynamic": ["requested_by"]},
        "variables": _vars(),
        "is_active": True,
    },
}


def _expand_recipients(config: dict | None) -> dict:
    config = deepcopy(config or {})
    preset = config.pop("preset", None)
    out = deepcopy(RECIPIENT_PRESETS.get(preset, {})) if preset else {}
    for key, value in config.items():
        if isinstance(value, list):
            merged = list(out.get(key, []))
            for item in value:
                if item not in merged:
                    merged.append(item)
            out[key] = merged
        elif value:
            out[key] = value
    return out


def get_registered_notification_events() -> dict[str, dict]:
    return deepcopy(NOTIFICATION_EVENTS)


def get_registered_notification_event(event_key: str) -> dict | None:
    event = NOTIFICATION_EVENTS.get((event_key or "").strip())
    return deepcopy(event) if event is not None else None


def register_notification_event(event_key: str, config: dict) -> None:
    key = (event_key or "").strip()
    if not key:
        raise ValueError("event_key is required")
    NOTIFICATION_EVENTS[key] = deepcopy(config)


def event_default_rule_config(event_key: str, event: dict | None = None) -> dict:
    event = deepcopy(event or NOTIFICATION_EVENTS[event_key])
    recipients = _expand_recipients(event.get("default_recipients"))
    return {
        "event_key": event_key,
        "label": event.get("label") or event_key.replace("_", " ").title(),
        "description": event.get("description") or "",
        "category": event.get("category") or "general",
        "priority": event.get("priority") or "normal",
        "title_template": event.get("default_title") or "{{ notification_title }}",
        "body_template": event.get("default_body") or "{{ notification_body }}",
        "cta_label_template": event.get("default_cta_label") or None,
        "cta_url_template": event.get("default_cta_url") or None,
        "recipient_mode": event.get("recipient_mode") or ("mixed" if len([k for k, v in recipients.items() if v]) > 1 else (next(iter(recipients.keys()), "project_members"))),
        "recipient_config": recipients,
        "condition_config": event.get("default_conditions") or {},
        "exclude_actor": event.get("exclude_actor", True),
        "dedupe_enabled": event.get("dedupe_enabled", True),
        "dedupe_window_minutes": int(event.get("dedupe_window_minutes", 30) or 30),
        "source": event.get("source") or event.get("source_feature") or "",
        "available_variables": event.get("variables") or [],
        "default_config": event,
        "is_deprecated": bool(event.get("status") == "deprecated" or event.get("is_deprecated")),
        "is_active": bool(event.get("is_active", True)),
    }
